account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('signup/', views.Signup.as_view(), name='signup'),
    path('logout/', views.logout, name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('' , include('page.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('account/', include('django.contrib.auth.urls')),
    
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

page/urls.py
from django.urls import path

app_name = 'page'

from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('contact/', views.contact, name='contact'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('services/', views.services, name='services'),
]

account/models.py
import random

from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    GENDER_CHOICES = [
        ('M', 'Man'),
        ('W', 'Woman'),
    ]

    gender = models.CharField(default='M', choices=GENDER_CHOICES, max_length=1)
    job = models.CharField(max_length=200)
    image = models.ImageField(upload_to='cover/profile/', blank=True)
    
    def __str__(self):
        return self.username
    
    def save(self, *args, **kwargs):
        if self.first_name == '':
            self.first_name = self.username
        if self.image == '':
            if self.gender == 'M':
                self.image = random.choice(['defualt/card2.png', 'defualt/card4.png'])
            elif self.gender == 'W':
                self.image = random.choice(['defualt/card1.png', 'defualt/card3.png'])
        return super().save(*args, **kwargs)

page/models.py
from django.db import models


class SortByDateTime(models.Manager):
    def get_queryset(self):
        return super().get_queryset().order_by('name')


class Portfolio(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='cover/portfolio/')

    objects = SortByDateTime()
    
    def __str__(self):
        return self.name

account/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from django import forms

class SignupForm(UserCreationForm):
    
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'job', 'gender')
        

class ChangeUserForm(UserChangeForm):
    
    class Meta:
        model = get_user_model()
        fields = "__all__"
        

account/views.py
from django.shortcuts import redirect, render
from django.views.generic import View
from django.contrib import auth
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST

from .forms import SignupForm


class Login(View):
    template_name = 'registration/login.html'

    def get(self, request):
        
        return render(request, template_name=self.template_name)

    def post(self, request):
        user = auth.authenticate(request,
                                 username=request.POST.get('username'),
                                 password=request.POST.get('password'),
                                 )
        if user is not None:
            auth.login(self.request, user)
            # messages.success(self.request, 'you are login')
            return redirect('page:home')
        else:
            # messages.error(self.request,
            #                format_html('The password is wrong or you have not registered. if you signup click <a href="{}">Sing Up</a>'.format(reverse('account:signup'))))
            return redirect('page:home')


class Signup(View):
    
    @method_decorator(require_POST)
    def post(self, request):
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            user = auth.authenticate(request, username=request.POST.get('username'), password=request.POST.get('password1'))
            auth.login(request, user=user)
            return redirect('page:home')
        else:
            return redirect('account:login')
        


def logout(request):
    if request.user.is_authenticated:
        auth.logout(request)
        messages.success(request, 'You are logout')
    return redirect('page:home')

page/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model

from .models import Portfolio



def index(request):
    teams = get_user_model().objects.filter(is_staff=False, is_superuser=False, is_active=True)[:4]
    return render(request, 'page/index.html', {'teams': teams})


def portfolio(request):
    portfolios = Portfolio.objects.all()
    
    return render(request, 'page/portfolio.html', {'portfolios': portfolios})


def services(request):
    
    return render(request, 'page/services.html')


def contact(request):
    
    return render(request, 'page/contact.html')

page/templates/page/contact.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/contact.css' %}">        
{% endblock %}

{% block content %}
    <!-- Content Section -->
    <section>
        <div class="container">
            <div class="contentHead">
                <h2>Contact Us</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
            </div>
            <div class="contentDown">
                <div>
                    <form action="./contact.html" method="get">
                        <label >Name</label>
                        <input type="text">
                        <label >Email</label>
                        <input type="email">
                        <label >Message</label>
                        <textarea ></textarea>
                        <button type="submit" >Submit</button>
                    </form>
                </div>
                <div>
                    <img src="{% static 'img/map.png' %}" alt="">
                </div>
            </div>
        </div>
    </section>

    {% endblock %}

page/templates/page/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <title>Startup Website</title>
</head>
<body>

    <!-- Header Section -->
    <header>
        <div class="container">
            <div>
                <div>
                    <nav>
                        <div>
                            <a href="{% url 'page:home' %}">
                                <img class="logoResponsive" src="{% static 'img/Logo.png' %}" alt="Logo">
                            </a>
                        </div>
                        <div class="hamMenu"><a href="{% url 'page:home' %}"><i class="fa-solid fa-bars fa-2xl"></i></a></div>
                        <div class="navItemResponsive">
                            <ul class="navItem">
                                {% if user.is_authenticated %}
                                <li><a href="{% url 'account:logout' %}">Logout</a><a href="{% url 'admin:login' %}">{{ user }}</a></li>
                                {% else %}
                                <li><a href="{% url 'account:login' %}">login/signup</a></li>
                                {% endif %}
                                <li><a href="{% url 'page:contact' %}">contact</a></li>
                                <li><a href="{% url 'page:services' %}">Services</a></li>
                                <li><a href="{% url 'page:portfolio' %}">Portfolio</a></li>
                                <li><a href="{% url 'page:home' %}">Home</a></li>
                            </ul>
                        </div>
                    </nav>
                </div>
                <div class="headerDown">
                    <div class="headerContent">
                        <h3 class="headerh3">Welcome</h3>
                        <h1 class="headerh1">Lorem ipsum dolor sit amet consectetur</h1>
                        <p class="headerp">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit nemo hic
                            quos, ab, dolor aperiam nobis cum est eos error ipsum, voluptate culpa nesciunt delectus
                            iste?</p>
                        <button>Explore</button>
                    </div>
                    <div>
                        <img src="{% static 'img/headerPic.png' %}" alt="groupPic" width="550px" height="350px">
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Content Section 1 -->
    <section>
        <div class="container">
            <div class="Section1">
                <div class="section1Content">
                    <h4 class="sectionh4">Partners</h4>
                    <h2 class="sectionh2">Lorem, ipsum dolor</h2>
                    <p class="sectionp">Lorem ipsum dolor sit amet consectetur adipisicing elit</p>
                </div>
                <div>
                    <div class="logoSection">
                        <a href="https://www.google.com/"><img src="{% static 'img/googleLogo.png' %}" alt="googlelogo"></a>
                        <a href="https://www.microsoft.com/en-us/"><img src="{% static 'img/microsoftLogo.png' %}" alt="microsoftlogo"></a>
                        <a href="https://www.airbnb.com/"><img src="{% static 'img/airbnbLogo.png' %}" alt="airbnblogo"></a>
                        <a href="#"><img src="{% static 'img/facebookLogo.png' %}" alt="facebooklogo"></a>
                        <a href="#"><img src="{% static 'img/spotifyLogo.png' %}" alt="spotifylogo"></a>
                    </div>
                    <div class="buttonSectionDiv">
                        <button class="buttonSection">Learn More</button>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Content Section 2 -->
    <section>
        <div class="container">
            <div class="Section2">
                <div>
                    <img src="{% static 'img/Section2img.png' %}" alt="groupPic2" width="500px" height="350px">
                </div>
                <div class="Section2content">
                    <h2 class="section2h2">Lorem ipsum dolor sit amet consectetur</h2>
                    <p class="section2p">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit nemo hic
                        quos, ab, dolor aperiam nobis cum est eos error ipsum, voluptate culpa nesciunt delectus
                        iste?</p>
                    <button class="buttonSection2">Learn More</button>
                </div>
            </div>
        </div>
    </section>

    <!-- Content Section 3 -->
    <section>
        <div class="container">
            <div class="Section3">

                <div class="Section2content">
                    <h2 class="section2h2">Lorem ipsum dolor sit amet consectetur</h2>
                    <p class="section2p">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit nemo hic
                        quos, ab, dolor aperiam nobis cum est eos error ipsum, voluptate culpa nesciunt delectus
                        iste?</p>
                    <button class="buttonSection2">Learn More</button>
                </div>
                <div>
                    <img src="{% static 'img/Section3img.png' %}" alt="groupPic2" width="500px" height="450px">
                </div>
            </div>
        </div>
    </section>

    <!-- Cards -->
    <section>
        <div class="container">
            <div class="cardSection">
                <div class="cardContent">
                    <h4 class="cardh4">Team</h4>
                    <h2 class="cardh2">Our Talents</h2>
                    <p class="cardp">Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit deleniti officia
                        odio vero.</p>
                </div>
                <div class="card">
                    {% for team in teams %}
                    <div class="cardinner">
                        <div class="cardimginner">
                            <img class="imginnercard" src="{{ team.image.url }}" alt="card1">
                        </div>
                        <div class="cardContentInner">
                            <h4>{{ team.get_full_name|title }}</h4>
                            <p>{{ team.job }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="cardSectionButton">
                    <button class="buttonCard">View Team</button>
                </div>
            </div>
        </div>
    </section>

{% include 'partials/__footer__.html' %}

</body>
</html>

page/templates/page/portfolio.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/portfolio.css' %}">
{% endblock %}

{% block content %}
<!-- Content Section -->
    <section>
        <div class="container">
            <div class="sampleContent">
                <h2 >Portfolio</h2>
                <p >Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
            </div>
            <div class="samplesImg">
                {% for portfolio in portfolios %}
                    <img src="{{ portfolio.image.url }}" alt="{{ portfolio.name }}">
                {% endfor %}
            </div>
            <div class="buttonSectionDiv">
                <button class="buttonSection">Learn More</button>
            </div>
        </div>
    </section>
{% endblock %}

page/templates/page/services.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/services.css' %}">
{% endblock %}

{% block content %}
    <!-- Content Section -->
    <section>
        <div class="container">
            <div class="contentHead">
                <h4>PLANS</h4>
                <h2>Our Services</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
            </div>
            <div class="serviceCard">
                <div class="innerCard">
                    <div>
                        <h4>Basic</h4>
                        <p><strong>$100</strong>/month</p>
                        <p style="color:rgba(33, 37, 41, 0.5);
                        ">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magnam temporibus at debitis id
                            obcaecati laboriosam.</p>
                    </div>
                    <div>
                        <h6><i class="fa-solid fa-check" style="color: #63E6BE;"></i> Lorem ipsum dolor sit.</h6>
                        <h6><i class="fa-solid fa-check" style="color: #63E6BE;"></i> Lorem ipsum dolor sit.</h6>
                        <h6><i class="fa-solid fa-check" style="color: #63E6BE;"></i> Lorem ipsum dolor sit.</h6>
                        <h6><i class="fa-solid fa-check" style="color: #63E6BE;"></i> Lorem ipsum dolor sit.</h6>
                    </div>
                    <div class="buttonSectionDiv">
                        <button class="buttonSection">Learn More</button>
                    </div>
                </div>
                <div class="innerCard">
                    <div>
                        <h4>Plus</h4>
                        <p><strong>$250</strong>/month</p>
                        <p style="color:rgba(33, 37, 41, 0.5);
                        ">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magnam temporibus at debitis id
                            obcaecati laboriosam.</p>
                    </div>
                    <div>
                        <h6><i class="fa-solid fa-check" style="color: #63E6BE;"></i> Lorem ipsum dolor sit.</h6>
                        <h6><i class="fa-solid fa-check" style="color: #63E6BE;"></i> Lorem ipsum dolor sit.</h6>
                        <h6><i class="fa-solid fa-check" style="color: #63E6BE;"></i> Lorem ipsum dolor sit.</h6>
                        <h6><i class="fa-solid fa-check" style="color: #63E6BE;"></i> Lorem ipsum dolor sit.</h6>
                    </div>
                    <div class="buttonSectionDiv">
                        <button class="buttonSection">Learn More</button>
                    </div>
                </div>
                <div class="innerCard">
                    <div>
                        <h4>Pro</h4>
                        <p><strong>$400</strong>/month</p>
                        <p style="color:rgba(33, 37, 41, 0.5);
                        ">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magnam temporibus at debitis id
                            obcaecati laboriosam.</p>
                    </div>
                    <div>
                        <h6><i class="fa-solid fa-check" style="color: #63E6BE;"></i> Lorem ipsum dolor sit.</h6>
                        <h6><i class="fa-solid fa-check" style="color: #63E6BE;"></i> Lorem ipsum dolor sit.</h6>
                        <h6><i class="fa-solid fa-check" style="color: #63E6BE;"></i> Lorem ipsum dolor sit.</h6>
                        <h6><i class="fa-solid fa-check" style="color: #63E6BE;"></i> Lorem ipsum dolor sit.</h6>
                    </div>
                    <div class="buttonSectionDiv">
                        <button class="buttonSection">Learn More</button>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block css %}
        
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <title>Startup Website {% block title %} {% endblock %}</title>
</head>
<body>

{% include 'partials/__header__.html' %}

{% block content %}
{% endblock %}

{% include 'partials/__footer__.html' %}


<script src="{% static 'JS/index.js' %}"></script>

</body>

</html>

templates/partials/__footer__.html
    {% load static %}
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="footerSection">
                <div class="footerIconSection">
                    <a href="#">
                        <img src="{% static 'img/facebook icon.svg' %}" alt="ficon">
                    </a>
                    <a href="#">
                        <img src="{% static 'img/insta icon.svg' %}" alt="iicon">
                    </a>
                    <a href="#">
                        <img src="{% static 'img/twiter icon.svg' %}" alt="twicon">
                    </a>
                    <a href="#">
                        <img src="{% static 'img/pin icon.svg' %}" alt="picon">
                    </a>
                    <a href="#">
                        <img src="{% static 'img/tik icon.svg' %}" alt="ticon">
                    </a>
                    <a href="#">
                        <img src="{% static 'img/whats icon.svg' %}" alt="wicon">
                    </a>
                    <a href="#">
                        <img src="{% static 'img/youtube icon.svg' %}" alt="yicon">
                    </a>
                </div>
                <div class="footerCopyright">
                    <p>© Start, 2022. All rights reserved.</p>
                </div>
            </div>
        </div>
    </footer>

templates/partials/__header__.html
    {% load static %}

    <!-- Header Section -->
    <header>
        <div class="container">
            <div>
                <nav>
                    <div>
                        <a href="#">
                            <img class="logoResponsive" src="{% static 'img/Logo.png' %}" alt="Logo">
                        </a>
                    </div>
                    <div class="hamMenu"><a href="{% url 'page:home' %}"><i class="fa-solid fa-bars fa-2xl"></i></a></div>
                    <div class="navItemResponsive">
                        <ul class="navItem">
                            {% if user.is_authenticated %}
                            <li><a href="{% url 'account:logout' %}">Logout</a><a href="{% url 'admin:login' %}">{{ user }}</a></li>
                            {% else %}
                            <li><a href="{% url 'account:login' %}">login/Signup</a>
                            {% endif %}
                            <li><a href="{% url 'page:contact' %}">contact</a></li>
                            <li><a href="{% url 'page:services' %}">Services</a></li>
                            <li><a href="{% url 'page:portfolio' %}">Portfolio</a></li>
                            <li><a href="{% url 'page:home' %}">Home</a></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </header>